# Generated by Django 4.0.2 on 2022-02-16 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_alter_foodcard_category_productscart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productscart',
            options={'verbose_name': "Product's carts", 'verbose_name_plural': "Product's cart"},
        ),
        migrations.AlterField(
            model_name='productscart',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
